### ISSUE TITLE
Display a start game button.

### ISSUE THREAD

**Issue by felixmerz00** [sopra-fs23-group-05/Server#33]

**Comment by Meleac** [comment]
9065f04f60ea018e79f8b1de419c5d98748f4a83

**Comment by Meleac** [comment]
9065f04f60ea018e79f8b1de419c5d98748f4a83

**Comment by Meleac** [comment]
https://github.com/sopra-fs23-group-05/Client/pull/51/commits/9065f04f60ea018e79f8b1de419c5d98748f4a83
