### ISSUE TITLE
As a lobby leader I want to change the settings to change the number of rounds, the time per round and the topic of the words. 

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#6]
- [ ] Only the lobby leader can change the settings. 
- [ ] As lobby leader you can choose a topic from a list of topics. 
- [ ] As lobby leader you can choose if the game is played with a chat or with a canvas or both.

**Comment by mxkso** [comment]
97af585 af37bc6

**Comment by mxkso** [comment]
af37bc6
97af585

**Comment by mxkso** [comment]
af37bc6

**Comment by mxkso** [comment]
af37bc69433486c7a063ea9c2f202a6194aaf8d7

**Comment by mxkso** [comment]
97af58554f77f40fc51b8b33e09d0d59e2628c62

**Comment by mxkso** [comment]
https://github.com/sopra-fs23-group-05/Client/commit/af37bc69433486c7a063ea9c2f202a6194aaf8d7
