### ISSUE TITLE
Store the lobby in the database record.

### ISSUE THREAD

**Issue by Meleac** [sopra-fs23-group-05/Server#97]

**Comment by felixmerz00** [comment]
f3a646d6b2b62d969b8434a638059652d27247ab

**Comment by felixmerz00** [comment]
0b62b08ed13ba658c514bdac9e22cc59c8c2690b
2f31c3d1a0c04f60d32bf89f440901c2bdabb1e7
3aa37b54744ed0c57a26d9605c2e2aa6e628b33a
